esphome:
  name: entrance
  friendly_name: Entrance
  libraries:
    - https://github.com/homy-newfs8/libsesame3bt#0.9.0
    - davetcc/TaskManagerIO @ ^1.4.0
  platformio_options:
    build_flags:
      - -std=gnu++17 -Wall -Wextra
      - -DMBEDTLS_DEPRECATED_REMOVED -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
      - -DTM_ENABLE_CAPTURED_LAMBDAS
    build_unflags:
      - -std=gnu++11
external_components:
  - source: 'components'
  # - source:
  #     type: git
  #     url: https://github.com/homy-newfs8/esphome-sesame3
  #   components: [ sesame_lock ]

esp32:
  # board: seeed_xiao_esp32c3
  # board: m5stack-atoms3
  # variant: esp32s3
  board: m5stick-c
  framework:
    type: arduino
    version: latest
    platform_version: 6.3.2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passphrase

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sesame Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

# Supported devices examples
# Choose one or more you want to use
# It seems that you can only connect up to 3 devices. I don't know why.
lock:
  - platform: sesame_lock
    name: Lock1
    id: lock_1
    # model: Requried: sesame_3 / sesame_4 / sesame_bot / sesame_bike / sesame_5 / sesame_5_pro
    model: sesame_5
    # public_key: Required for sesame_3 / sesame_4 / sesame_bot / sesame_bike
    # for sesame_5 / sesame_5_pro comment out public_key line or specify any string (will be ignored)
    public_key: ""
    secret: !secret sesame5_secret
    address: !secret sesame5_address
  - platform: sesame_lock
    name: Lock2
    id: lock_2
    model: sesame_3
    public_key: !secret sesame3_pubkey
    secret: !secret sesame3_secret
    address: !secret sesame3_address
  - platform: sesame_lock
    name: Bot1
    id: bot_1
    model: sesame_bot
    public_key: !secret sesamebot_pubkey
    secret: !secret sesamebot_secret
    address: !secret sesamebot_address
  # - platform: sesame_lock
  #   name: Bike1
  #   id: bike_1
  #   model: sesame_bike
  #   public_key: !secret sesamebike_pubkey
  #   secret: !secret sesamebike_secret
  #   address: !secret sesamebike_address
