esphome:
  name: sesame
  libraries:
    - symlink://../../../../../../PlatformIO/Projects/libsesame3bt
    - davetcc/TaskManagerIO @ ^1.4.0
  platformio_options:
      build_flags:
        - -std=gnu++17 -Wall -Wextra
        - -DMBEDTLS_DEPRECATED_REMOVED -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
        - -DTM_ENABLE_CAPTURED_LAMBDAS
      build_unflags:
        - -std=gnu++11
external_components:
  - source: 'custom_components'

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passphrase

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sesame Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

lock:
  - platform: sesame_lock
    name: Sesame 1
    id: sesame_lock_1
    public_key: !secret sesame_pubkey
    secret: !secret sesame_secret
    address: !secret sesame_address
    on_lock:
    - logger.log: "door locked"
    - lock.lock: sesame_lock_2
  - platform: sesame_lock
    name: Sesame 2
    id: sesame_lock_2
    public_key: !secret sesame_pubkey
    secret: !secret sesame_secret
    address: !secret sesame_address2
